version: '3'
services: 
  app:
    build: . 
    ports:
      - 7000:8080
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    command: /bin/sh
    environment:
      - CHOKIDAR_USEPOLLING=true
